"""added archival logic to table

Revision ID: 0416c872a522
Revises: d42c05f66366
Create Date: 2026-04-14 13:51:19.320168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0416c872a522'
down_revision = 'd42c05f66366'
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column(
        'habits',
        sa.Column('is_archived', sa.Boolean(), nullable=True, server_default=sa.false())
    )
    op.add_column(
        'habits',
        sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        'habits',
        sa.Column('archived_reason', sa.String(length=100), nullable=True)
    )
    op.add_column(
        'habits',
        sa.Column('archived_note', sa.Text(), nullable=True)
    )

    op.execute("UPDATE habits SET is_archived = 0 WHERE is_archived IS NULL")

    with op.batch_alter_table('habits') as batch_op:
        batch_op.alter_column('is_archived', nullable=False, server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits') as batch_op:
        batch_op.drop_column('archived_note')
        batch_op.drop_column('archived_reason')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
