"""added entry_type and structured_content

Revision ID: 06f9f427a1e9
Revises: b9e66e0dedbd
Create Date: 2026-04-07 13:47:02.940957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f9f427a1e9'
down_revision = 'b9e66e0dedbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('structured_content', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('structured_content')
        batch_op.drop_column('entry_type')

    # ### end Alembic commands ###
