"""added AI insights table for simple journal entries

Revision ID: 34d0c02d9b7f
Revises: 2be2c7ab7403
Create Date: 2026-04-09 14:33:59.213928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d0c02d9b7f'
down_revision = '2be2c7ab7403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=False),
    sa.Column('distortions', sa.JSON(), nullable=True),
    sa.Column('reframe', sa.Text(), nullable=False),
    sa.Column('assessment', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_ai_analysis')
    # ### end Alembic commands ###
