"""fixed date format in HabitLog

Revision ID: 7b403d63dfda
Revises: 7899fe03fc4c
Create Date: 2026-04-01 14:18:31.739891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b403d63dfda'
down_revision = '7899fe03fc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.create_unique_constraint('unique_habit_per_day', ['habit_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('unique_habit_per_day', type_='unique')
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
