"""added procrastination_sheet table

Revision ID: 7fc1934f6b62
Revises: 1b7e078d72a6
Create Date: 2026-04-13 11:48:24.281911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc1934f6b62'
down_revision = '1b7e078d72a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procrastination_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=500), nullable=False),
    sa.Column('avoidence_reason', sa.Text(), nullable=True),
    sa.Column('expected_difficulty', sa.Integer(), nullable=False),
    sa.Column('expected_statisfaction', sa.Integer(), nullable=False),
    sa.Column('resistance_thoughts', sa.Text(), nullable=True),
    sa.Column('tiny_steps', sa.Text(), nullable=False),
    sa.Column('actual_difficulty', sa.Integer(), nullable=False),
    sa.Column('actual_statisfaction', sa.Integer(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procrastination_sheet')
    # ### end Alembic commands ###
