"""added weekly_insights to database

Revision ID: 9e0f636177ab
Revises: 06fbf26f6885
Create Date: 2026-04-15 13:13:33.196775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0f636177ab'
down_revision = '06fbf26f6885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('patterns', sa.JSON(), nullable=True),
    sa.Column('contradictions', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('sufficiency_level', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('contradiction_flag', sa.Boolean(), nullable=False),
    sa.Column('signals_used', sa.JSON(), nullable=True),
    sa.Column('structured_context', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_weekly_insight_user_week')
    )
    with op.batch_alter_table('weekly_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_insights_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_insights_week_start'), ['week_start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_insights_week_start'))
        batch_op.drop_index(batch_op.f('ix_weekly_insights_user_id'))

    op.drop_table('weekly_insights')
    # ### end Alembic commands ###
