"""added created_at to habit logs

Revision ID: c94a0722c5c0
Revises: 3f9f6ed3eaf5
Create Date: 2026-04-27 13:13:24.015630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94a0722c5c0'
down_revision = '3f9f6ed3eaf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
