"""refactor procrastination sheets into sheets and task models

Revision ID: d42c05f66366
Revises: 7fc1934f6b62
Create Date: 2026-04-13 13:29:12.861747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42c05f66366'
down_revision = '7fc1934f6b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procrastination_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procrastination_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('avoidance_reason', sa.Text(), nullable=True),
    sa.Column('resistance_thoughts', sa.Text(), nullable=True),
    sa.Column('tiny_step', sa.Text(), nullable=False),
    sa.Column('expected_difficulty', sa.Integer(), nullable=False),
    sa.Column('expected_satisfaction', sa.Integer(), nullable=False),
    sa.Column('actual_difficulty', sa.Integer(), nullable=True),
    sa.Column('actual_satisfaction', sa.Integer(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sheet_id'], ['procrastination_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('procrastination_sheet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procrastination_sheet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('avoidence_reason', sa.TEXT(), nullable=True),
    sa.Column('expected_difficulty', sa.INTEGER(), nullable=False),
    sa.Column('expected_statisfaction', sa.INTEGER(), nullable=False),
    sa.Column('resistance_thoughts', sa.TEXT(), nullable=True),
    sa.Column('tiny_steps', sa.TEXT(), nullable=False),
    sa.Column('actual_difficulty', sa.INTEGER(), nullable=False),
    sa.Column('actual_statisfaction', sa.INTEGER(), nullable=False),
    sa.Column('reflection', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('procrastination_tasks')
    op.drop_table('procrastination_sheets')
    # ### end Alembic commands ###
