"""added updated_at column

Revision ID: e3c6e1539794
Revises: e64f85a7ebb6
Create Date: 2026-04-22 13:42:49.520470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c6e1539794'
down_revision = 'e64f85a7ebb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_ai_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_ai_analysis', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
