"""added updated_at column to JournalEntry

Revision ID: e64f85a7ebb6
Revises: b68bffd16b56
Create Date: 2026-04-22 13:14:54.512506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64f85a7ebb6'
down_revision = 'b68bffd16b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
